name: cry
description: 一个Flutter组件库，包含button、form、dataTable、dialog、imageUpload、root、toggleButton、transfer、treeTable、menu
version: 1.1.7
homepage: http://www.cairuoyu.com/
publish_to: https://pub.dev
#publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.0
  dio: ^4.0.0
  global_configuration: ^2.0.0-nullsafety.0
  intl: ^0.17.0
  date_format: ^2.0.2
  image_picker: ^0.7.3
  image_picker_for_web: ^2.0.0
  file_picker: ^3.0.0
  flutter_markdown: ^0.6.1
  fluttertoast: ^8.0.3

flutter:

flutter_intl:
  enabled: true
